### ISSUE TITLE
MudThemeManager - Open Source

### ISSUE THREAD

**Issue by rakeshkgsg** [Garderoben/MudBlazor.Templates#11]
Hi guys,

Great work with the mud theme. Also love the work done on the mudthememanager. Was wondering if we could get the source of the manager as we are looking to integrate that into a more generic right side panel. Also hoping to learn more about it and maybe the community can help with the implementation of the missing elements.

Thanks,
Rakesh

**Comment by Garderoben** [comment]
@rakeshkgsg its open source now!
https://github.com/Garderoben/MudBlazor.ThemeManager
