### ISSUE TITLE
Feature Request: MudAutoComplete, set list width

### ISSUE THREAD

**Issue by zmagickap** [Garderoben/MudBlazor.Templates#13]
I think there'd be great value in being able to set the width of the filtered list independently of the MudAutoComplete component.

Maybe the component only displays 50 characters and truncates the rest.

But as I type, I want to see 100 or 150 characters or so, in order to see the entire value so I can select the right one.

**Comment by henon** [comment]
Please open an issue in MudBlazor not MudBlazor.Templates, thanks.
