### ISSUE TITLE
project creation error when application name has hyphen

### ISSUE THREAD

**Issue by antidemon** [Garderoben/MudBlazor.Templates#134]
Followed https://www.mudblazor.com/getting-started/installation#using-our-dotnet-templates to create a new project but had an error on this command:
`dotnet new mudblazor --host wasm --name dashboard-demo`

> The template "MudBlazor Templates" was created successfully.
> 
> Processing post-creation actions...
> Running 'dotnet restore' on C:\Source\repos\Dud\...
> C:\Program Files\dotnet\sdk\6.0.202\NuGet.targets(289,5): error MSB3202: The project file "C:\Source\repos\Dud\dashboard_demo.csproj" was not found. [C:\Source\repos\Dud\dashboard-demo.sln]
> Restore failed.
> Post action failed.
> Manual instructions: Run 'dotnet restore'

The solution file has:
`Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "dashboard_demo", "dashboard_demo.csproj", "{31840BA8-8B37-4929-9BCF-414518ACB738}"`

but the project file is called
`dashboard-demo.csproj`

**Comment by sambhavyadav90** [comment]
- Actual behavior

The original Source Name gets replaced with dashboard_demo inside source files (e.g. in the .sln file or the server's Program.cs) but with dashboard-demo in file and folder names.

The mismatch between paths expected by the .sln file (it expects the projects in dashboard_demo and dashboard_demo folders while they actually are in dashboard-demo. and dashboard-demo folders) breaks the .sln file and thus the template's build.

- You can create a new project like "dahsboard.demo"
- dotnet new mudblazor --host wasm --name dahsboard.demo

**Comment by antidemon** [comment]
Thanks for the workaround suggestions but I just edited the sln file manually.

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
