### ISSUE TITLE
Does MudBazor Templates break CSS Isolation?

### ISSUE THREAD

**Issue by zmagickap** [Garderoben/MudBlazor.Templates#14]
I just tried the vary basic CSS Isolation example from [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0) in my project using MudBlazor Template for Server. The Administrator version.

The isolated CSS does not update the H1.

But if I create a new default Blazor app and do the exact same example, it works. H1 color updates.

Others have assured me that CSS Isolation works with the MudBlazor library, so the only variable I can think of is something in Templates is blocking it.

Anyone?

EDIT: I guess the follow up question would be: How can I get CSS Isolation to work in the Template?

**Comment by zmagickap** [comment]
SOLUTION:

It turns out that in order for CSS Isolation to function, there needs to be a specific reference to a stylesheet in _Host.cshtml.

This appears to be auto generated in the default Blazor project, but it appears MudBlazor.Templates took it out.

The reference needs to be:
`<link href="(ProjectName).styles.css" rel="stylesheet" />`

When I added that line, the ::deep worked with CSS Isolation.

**Comment by henon** [comment]
Do we have to fix this here or is it something everyone has to do for themselves and we should document it?

**Comment by Garderoben** [comment]
I have turned it off, as you noticed you can activate it again.
