### ISSUE TITLE
PWA template does not allow app to download and install

### ISSUE THREAD

**Issue by NateVolt** [Garderoben/MudBlazor.Templates#146]
Out of the box the `wasm-pwa` template the app can not be installed once launched in a web browser. Looking through chrome console errors I found the manifest specifies two different icons, but only one icon is provided in the wwwroot assets folder.

By removing the 192x192 icon entry from the manifest I cleared up the errors and the download and install option was available.

**Comment by NateVolt** [comment]
Can I open a PR? I don't see any contribution guides in this repo.

**Comment by JonBunator** [comment]
Thanks for the bug report. We would appreciate a PR. The contribution guidelines are the same as the one in the main repo

**Comment by NateVolt** [comment]
@JonBunator  I apologize if this is a dumb question, but should I be able to simply open a PR? 

I have not done this for open source before, only for personal and org repos. I do not have write access to publish my branch.

Once I have that solved I will push my changes.

**Comment by JonBunator** [comment]
Fork the repo and push your branch to your fork. Then you can open a PR. You don't have to push your branch to this repo

**Comment by NateVolt** [comment]
Got it. Thanks for clarifying.
