### ISSUE TITLE
Where is the mudblazor admin template?

### ISSUE THREAD

**Issue by misterraj7** [Garderoben/MudBlazor.Templates#148]
Where do we get the admin dashboard template?

The admin dashboard with mudblazor looks like this,

https://github.com/TheDayIsMyEnemy/BlazorTemplates/raw/admin-dashboard/content/AdminDashboardTemplate.png

Is this not available now? Is it deprecated?
Please throw some ideas

Thanks

**Comment by JonBunator** [comment]
See #122
