### ISSUE TITLE
AdminDashboard Repository

### ISSUE THREAD

**Issue by LuisThe0ne** [Garderoben/MudBlazor.Templates#182]
Hey!

In your latest release is the Info that the Admin Dahsboard Template will get it's own Repo.
Any Link to that Repo, or any info?

Greetings,
Luis

**Comment by pete1854** [comment]
Any news?

**Comment by ekjuanrejon** [comment]
any news?

**Comment by LuisThe0ne** [comment]
No

**Comment by arvinboggs** [comment]
The following is the last revision that has the admin template. https://github.com/MudBlazor/Templates/tree/df29a8de2733229fd6d297750b6bc4e39ee7e25d . 
It was commited in Feb 9, 2022.

**Comment by LuisThe0ne** [comment]
Thanks!
