### ISSUE TITLE
Project Type Missing Descriptions

### ISSUE THREAD

**Issue by Grauenwolf** [Garderoben/MudBlazor.Templates#183]
The "Project Type" drop-down has a `(i)` button, but it doesn't actually do anything. Nor is there any other descriptions for the different project types on the page.

The information on https://github.com/MudBlazor/Templates likewise doesn't describe the different hosting models.

**Comment by Grauenwolf** [comment]
This file appears to have the correct descriptions, so I'm not sure why it's not picking it up.

https://github.com/MudBlazor/Templates/blob/dev/src/.template.config/template.json

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
