### ISSUE TITLE
template package install fails on existing wasm PWA project

### ISSUE THREAD

**Issue by nagostoni** [Garderoben/MudBlazor.Templates#218]
I have an existing project created with "blazorwasm" template included in Visual Studio 2022, and i'd like to include MudBlazor in  it but i always encounter an error message that says:
 "the package 'MudBlazor.Templates 0.6.3' conteins a package type 'Template' that is not supported by the project <MyProject>.				
The same if i create a new project by "blazorwasm" and i try to add Mudblazor as second step. 
On the contrary, after installing the MudBlazor template in Visual Studio, if a create a new project with that template (wasm-PWA) the project is correctly created and it correctly runs.

I'm new on Mudblazor but looking into .cprj files and dependancies i noticed that in Mudblazor by template project i read:
  PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="**6.0.2**"
  PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="**6.0.2**" PrivateAssets="all"
  PackageReference Include="MudBlazor" Version="6.0.6"
while in my previous blazorwasm template project:
    PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="**6.0.9"** 
    PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="**6.0.9**" PrivateAssets="all" 

Even upgrading these two files to 6.0.10 version of  WebAssembly  nothing change.

Is this the problem ? How can i overcome it ? Or do i have to stay with 6.0.2 release of WebAssembly files ?

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
