### ISSUE TITLE
Are MainLayout.razor.css and NavMenu.razor.css needed?

### ISSUE THREAD

**Issue by nightroman** [Garderoben/MudBlazor.Templates#22]
Are MainLayout.razor.css and NavMenu.razor.css needed in `DefaultBlazor.Wasm`?
`DefaultBlazor.Server` template does not use those.
And I do not see any differences after removing from `DefaultBlazor.Wasm`, too.

**Comment by Garderoben** [comment]
@nightroman they are not needed, thanks. I have removed them now.
