### ISSUE TITLE
MudTable inline edit

### ISSUE THREAD

**Issue by sircoram** [Garderoben/MudBlazor.Templates#25]
Good Morning.
If you try editing a table and you press tab to pass from a field to another the row disappear causing unconsistent behaviour disappearing.
I think there is a big problem in inline editing. You can try with your own example:
https://try.mudblazor.com/snippet/maQlkVlndBPffYxw

Thank you

**Comment by Dunce001** [comment]
Hi - It works for me in Chrome, Firefox and Edge. You can always try setting TabIndex="1", TabIndex="2" on each form element within the RowEditingTemplate. Perhaps use a higher number set (TabIndex="30", 31 etc) to avoid any odd behavior with other elements.

**Comment by sircoram** [comment]
Hello.
Thank you for the response. I partially solved using AutoFocus="true".  Where I  cannot set this parameter is in a cell with a <MudSelect/>. Is there a way to do it?

But. I canno find TabIndex attribute. How did you  set it?
Thank you again!

**Comment by Dunce001** [comment]
I'm not sure about the AutoFocus, but I use TabIndex on all forms to control the flow when using TAB. It's not listed in the MudBlazor becasue it's a standard HTML attribute (but works as expected with MudBlazor elements).

So you would just add it to your elements, in the order that you want "Tabbing" to work.
<MudTextField @bind-Value="@context.Sign" Required TabIndex="1" />

So you could you 1-10 (or whatever) for your normal form elements, and perhaps 20-whatever for your RowEditingTemplate elements. This way, you shouldn't get any unexpected tabbing between the two.

<RowEditingTemplate>
<MudTextField @bind-Value="@context.Title" Required TabIndex="21" />
<MudTextField @bind-Value="@context.FirstName" Required TabIndex="22" />
<MudTextField @bind-Value="@context.LastName" Required TabIndex="23" /> 
...etc

**Comment by sircoram** [comment]
Ok. Thank you. I learned other thing.
But it seams not working with a Select element... :(

Thank you
