### ISSUE TITLE
MudNavLink API | ForceLoad not working!

### ISSUE THREAD

**Issue by liuvt** [Garderoben/MudBlazor.Templates#280]
Hi!
ForceLoad not working for me, when i try reload page.

My code :
![image](https://user-images.githubusercontent.com/43575705/223598537-38deac47-67c1-443c-8f6e-21921630c2c0.png)

**Comment by liuvt** [comment]
I try fix reload with OnClick it working but Match="NavLinkMatch.Prefix" not working  lol.
![image](https://user-images.githubusercontent.com/43575705/223599689-4429acb8-aa38-48d9-82c1-9a93a55c2260.png)
![image](https://user-images.githubusercontent.com/43575705/223599741-a30d7445-c5e6-4330-9fbf-f07e8fe6c880.png)
![image](https://user-images.githubusercontent.com/43575705/223600300-e9e0b02d-9e8d-413f-bc9e-e42f6ecdc1bc.png)

**Comment by elgransan** [comment]
I'm having the same issue
![image](https://user-images.githubusercontent.com/9949584/229550293-6cf16a4b-fdeb-426c-a031-8ce7cde76dfb.png)
this is not reloading the page

**Comment by liuvt** [comment]
Dear Mr/Mrs,

To fix issue i inject navigation

<MudNavLink OnClick="@(() => _home())">Log Out</MudNavLink>

[Inject]
protected NavigationManager NavigationManager { get; set; }

protected async Task _home()
{
  NavigationManager.NavigateTo("/", true);
}

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
