### ISSUE TITLE
Template uses UseStaticWebAssets. Is this a security issue?

### ISSUE THREAD

**Issue by abgenullt** [Garderoben/MudBlazor.Templates#292]
Hi everyone,

I'm kind of new to blazor and MudBlazor.
But on this page from microsoft: [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-7.0), there is a warning to use static files for non development environments.

So, is adding this in any environment, like in this template, not an security issue?

And, if so, is there an alternative way to make this work?

Regards
abgenullt

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
