### ISSUE TITLE
Error when upgrading to NuGet package 5.0.1

### ISSUE THREAD

**Issue by Yomodo** [Garderoben/MudBlazor.Templates#3]
These are great templates!

I get an error when updating the NuGet package to MudBlazor 5.0.1:

![image](https://user-images.githubusercontent.com/10358198/108051946-c848bb80-704b-11eb-98f4-edc2d71dc41d.png)

What to do?

**Comment by veresvit** [comment]
You need to change Target framework to net5.0 in the project properties and update all depending nugets to 5.0.0 version.

**Comment by Garderoben** [comment]
@Yomodo missed this, i have since you posted this created the templates from scratch with .NET 5 in mind, they are updated to latest now.
