### ISSUE TITLE
Extra Project Generated when making WASM-PWA-Hosted Project

### ISSUE THREAD

**Issue by rgbalex** [Garderoben/MudBlazor.Templates#319]
Hi, 
When creating a new project using version 0.6.3 and selecting the WASM-PWA-Hosted Project type, an extra .csproj is created! 

![image](https://github.com/MudBlazor/Templates/assets/12647477/96327a17-b24d-4b4e-a977-ed783a53ecf6)

Steps to reproduce are of course creating a blank project with type WASM-PWA-Hosted

**Comment by FeuFeve** [comment]
Had the same issue

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
