### ISSUE TITLE
Remove launchSettings.json from template

### ISSUE THREAD

**Issue by mattheys** [Garderoben/MudBlazor.Templates#360]
### Bug type

Other

### What happened?

When attempting to have multiple solutions based off MudBlazor open at the same time all the IISExpress ports seem to be set to 61949.  Reading this SO article suggests removing the launchSettings.json before creating the template so that random numbers are generated. It has no votes though so not 100% this is the true answer or not. https://stackoverflow.com/questions/52818765/visual-studio-custom-project-template-applicationurl-port-number

### Expected behavior

The applicationUrl in the launchSettings.json has a randomly assigned port number.

### Reproduction link

https://github.com/MudBlazor/MudBlazor

### Reproduction steps

1.  Install MudBlazor templates  `dotnet new --install MudBlazor.Templates`
2.  Create a Folder called MudBlazor and two subfolders called App1 & App2
3.  Run `dotnet new mudblazor --host server --name App1` in App1 and `dotnet new mudblazor --host server --name App2` in App2
4. Compare the two launchSettings.json files to find they are identical
5. Open App1 in VS2022 and run it
6. While App1 is still running Open App2 in a new VS2022 and run it
7. Error
![image](https://user-images.githubusercontent.com/10292436/176160343-4ba75ce9-3399-41f2-98cf-e6779d57c41a.png)

### Version (bug)

0.6.2

### What browsers are you seeing the problem on?

Other

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattheys** [comment]
It's an easy work around to change the port number each time just wanted to make you aware if you weren't already, I couldn't find any other issues about it.

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
