### ISSUE TITLE
MudBlazor wasm template screws offline mode

### ISSUE THREAD

**Issue by FilipZamec** [Garderoben/MudBlazor.Templates#361]
### Bug type

Other

### What happened?

When I create new project using MudBlazor template: wasm pwa aspnet core hosted. 
Then there is one project unnecesarry. But major problem is that this project cannot be used offline. It says 404 error when trying. I'm using ofcoarse published release version.

But when I use standard blazor wasm project and add MudBlazor to project manually, then everything works. I couldn't find out where is the problem.

### Expected behavior

When I create Mudblazor wasm project and publish it. Load it for the first time and then stop the server. It should work.

### Reproduction link

create empty mudblazor project. thats it.

### Reproduction steps

1. Create empty MudBlazor wasm pwa aspnet core hosted project from MudBlazor template.
2. publish release version of it
3. Load this web in the browser and see it working.
4. Stop the server.
5. load this web again in the browser and watch 404 error.

### Version (bug)

6.0.9

### What browsers are you seeing the problem on?

Firefox, Chrome

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
