### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by madomodoki** [Garderoben/MudBlazor.Templates#382]
Hi.

A new server-based project was created using this template.
When I start building and debugging (without any editing !),
the sample website appears fine and appears to be working as expected.
However, when I look at the output window of the integrated development environment, I see the following error messages

Exception thrown: 'System.InvalidOperationException' in Microsoft.AspNetCore.Components.Server.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.JSInterop.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll

Is this the behavior intended by the developers?
![mudblazor](https://github.com/MudBlazor/Templates/assets/100444384/89313b6e-33d0-4a5a-8eed-d717207cd878)

**Comment by ScarletKuro** [comment]
Hi.

Yes, this is intended. This is swallowed exception from the prerendering when JSInterop is not available:
https://github.com/MudBlazor/MudBlazor/blob/c4915b813bf6770dc5f0a114c392de410ce37cf8/src/MudBlazor/Services/IIJSRuntimeExtentions.cs#L67
