### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by ikemyle** [Garderoben/MudBlazor.Templates#433]
Hello, I am trying to use .net 8 template but MudBlazorWebApp cannot be found when run
dotnet new mudblazorwebapp --interactivity Auto --output C:\temp\tests\mudTemplates\interactivityAuto

Please advise.

**Comment by sokoo78** [comment]
Same here. I can create a project from the wizard, but there is no option to include authentication. From command line, I get "template or option not found". Also the created project is .NET 6, not .NET 8.

**Comment by steveant** [comment]
> Same here. I can create a project from the wizard, but there is no option to include authentication. From command line, I get "template or option not found". Also the created project is .NET 6, not .NET 8.

Had the same issue yesterday and it looks like the latest .NET 8 code that installs the mudblazorwebapp template has not yet been published to nuget.org, so for now i swapped my install script to get the dev branch from github and it works (caveat is that this is day-to-day code so you're taking a risk on stability until the official release. Basically,

I replaced:
dotnet new install MudBlazor.Templates 

with:
git clone https://github.com/MudBlazor/Templates.git 
dotnet new install ./Templates/src/MudBlazorWebTemplate

that enabled this to work for me:
dotnet new mudblazorwebapp  --interactivity Auto --auth Individual 

GL!

**Comment by ikemyle** [comment]
Yes Steve, I did the same, but it was extra work. Better to have the template in nuget, especially when new updates come in.

**Comment by Elangovan4ever** [comment]
Same issue here. Thanks a lot for the workaround. Waiting for the Nuget update.

**Comment by kyledavi5** [comment]
Same issue. Waiting for the Nuget update as well. :)

**Comment by PatrickRainer** [comment]
The Workaround seems not to work in JetBrains rider. Get the Error Message: "Template is not Supported"

**Comment by Allann** [comment]
Still the same here.  Any eta?

**Comment by SirLefti** [comment]
Last update of the [template on nuget](https://www.nuget.org/packages/MudBlazor.Templates) was on 2022-07-27. 
The repository seems to be maintained, but the nuget package is apparently not. Wondering if there is any reason why.

**Comment by jasonhillva** [comment]
Still not in nuget as of today.

**Comment by henon** [comment]
I have made @Garderoben aware of this thread. I know he was working on publishing over the holidays but didn't complete it.

**Comment by jasonhillva** [comment]
> I have made @Garderoben aware of this thread. I know he was working on publishing over the holidays but didn't complete it.

Awesome, thanks for the hard work.  @Garderoben

**Comment by Garderoben** [comment]
I try to get it out this week sorry for delay!

You can always download the source and run the install file and use them until i release it.

**Comment by atrakic** [comment]
> I try to get it out this week sorry for delay!
> 
> You can always download the source and run the install file and use them until i release it.

Then I suggest main README.md to reflect install steps.

**Comment by atrakic** [comment]
On osX I have done: 

```
$ dotnet --version
6.0.414


# Install template:
$ git clone https://github.com/MudBlazor/Templates.git
$ dotnet new install -i ./Templates/src/MudBlazorWebTemplate


# Bootstrap new proj:
$ dotnet new mudblazorwebapp --interactivity Auto --auth Individual -o HelloWorld


# Enter new proj:
$ cd HelloWorld 

$ ls
HelloWorld        HelloWorld.Client HelloWorld.sln


# Try to build:
$ cd HelloWorld.Client
$  dotnet run
/usr/local/share/dotnet/sdk/6.0.414/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [/Users/adtr/src/github.com/MudBlazor/MudBlazor/examples/HelloWorld/HelloWorld.Client/HelloWorld.Client.csproj]

The build failed. Fix the build errors and run again.


# Try to build:
$ cd ../HelloWorld

$ dotnet run
Building...
/usr/local/share/dotnet/sdk/6.0.414/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [/Users/adtr/src/github.com/MudBlazor/MudBlazor/examples/HelloWorld/HelloWorld.Client/HelloWorld.Client.csproj]
/usr/local/share/dotnet/sdk/6.0.414/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [/Users/adtr/src/github.com/MudBlazor/MudBlazor/examples/HelloWorld/HelloWorld/HelloWorld.csproj]

The build failed. Fix the build errors and run again.
```

What else should be done here?

**Comment by chrisp0** [comment]
Template is targeting .NET 8 and your installed sdk is v6.0.414
So i think, you have to install latest .NET 8 SDK.

**Comment by atrakic** [comment]
> Template is targeting .NET 8 and your installed sdk is v6.0.414 So i think, you have to install latest .NET 8 SDK.

Ok but [getting started](https://mudblazor.com/getting-started/installation#manual-install-add-script-reference) refers to use Templates repo.

**Comment by chrisp0** [comment]
Yes, but the GettingStarted uses latest released template package.
You cloned the current template repo master and this targets .NET8.
Either install .NET8 SDK or install mudblazor templates from nuget (not from source).

Or wait for @Garderoben until he releases the new template package.

**Comment by Garderoben** [comment]
They are updated and released now with some changes, check the new readme.
