### ISSUE TITLE
Rendering does not Work correclty in "InteractivityAuto_AlliInteractive_auth"

### ISSUE THREAD

**Issue by PatrickRainer** [Garderoben/MudBlazor.Templates#437]
As soon you change to one of the Pages for the UserManagement, the rendering for the pages will not work anymore. 

For example the Counter Button or the Hamburger Button on the Drawer.

**Comment by ikemyle** [comment]
yes, the same here. It looks that is a problem with InteractiveAuto mode. In js I can see the error: blazor.web.js:1  Error: One or more errors occurred. (The JSON value could not be converted to Microsoft.AspNetCore.Components.RootComponentOperation[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.)
The login page which is server mode works as expected

**Comment by PatrickRainer** [comment]
I assume the issue has something to do with changing the Layout. So switching from Layout to AccountLayout and back.

Not sure is it possible to refer the js Scripts on the layout pages?

Other Ideas?
