### ISSUE TITLE
Invalid options (from Tutorial)

### ISSUE THREAD

**Issue by atrakic** [Garderoben/MudBlazor.Templates#449]
After failing to run on .Net 6x (see: https://github.com/MudBlazor/Templates/issues/433), I have descided to give a new try on .NET 8x under docker env. What I have done:

```
$ mkdir -p foo
$ cd foo
$ docker run -it --rm \
	-v "$PWD":/app -w /app \
	mcr.microsoft.com/dotnet/sdk:"8.0" 
```

## Under docker from here:
```
root@1c955b976efe:/app# ls -al
total 4
drwxr-xr-x 2 root root   64 Jan 15 10:48 .
drwxr-xr-x 1 root root 4096 Jan 15 10:49 ..

root@1c955b976efe:/app# dotnet  --version
8.0.100-rc.1.23463.5
```

## Install Template
```
root@1c955b976efe:/app# dotnet new install MudBlazor.Templates
The following template packages will be installed:
   MudBlazor.Templates

Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.cs.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.de.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.en.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.es.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.fr.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.it.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.ja.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.ko.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.pl.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.pt-BR.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.ru.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.tr.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.zh-Hans.json), it will be skipped from further processing.
Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.zh-Hant.json), it will be skipped from further processing.
Success: MudBlazor.Templates::0.6.5 installed the following templates:
Template Name      Short Name  Language  Tags
-----------------  ----------  --------  --------------------------------
MudBlazor Web App  mudblazor   [C#]      Web/Blazor/WebAssembly/MudBlazor
```

## Create new project (from tutorial):
```
root@1c955b976efe:/app# dotnet new mudblazor --host wasm --name MyApplication
Error: Invalid option(s):
--host
   '--host' is not a valid option
wasm
   'wasm' is not a valid option

For more information, run:
   dotnet new mudblazor -h

For details on the exit code, refer to https://aka.ms/templating-exit-codes#127
```

**Comment by Garderoben** [comment]
> After failing to run on .Net 6x (see: #433), I have descided to give a new try on .NET 8x under docker env. What I have done:
> 
> ```
> $ mkdir -p foo
> $ cd foo
> $ docker run -it --rm \
> 	-v "$PWD":/app -w /app \
> 	mcr.microsoft.com/dotnet/sdk:"8.0" 
> ```
> 
> ## Under docker from here:
> ```
> root@1c955b976efe:/app# ls -al
> total 4
> drwxr-xr-x 2 root root   64 Jan 15 10:48 .
> drwxr-xr-x 1 root root 4096 Jan 15 10:49 ..
> 
> root@1c955b976efe:/app# dotnet  --version
> 8.0.100-rc.1.23463.5
> ```
> 
> ## Install Template
> ```
> root@1c955b976efe:/app# dotnet new install MudBlazor.Templates
> The following template packages will be installed:
>    MudBlazor.Templates
> 
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.cs.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.de.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.en.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.es.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.fr.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.it.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.ja.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.ko.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.pl.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.pt-BR.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.ru.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.tr.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.zh-Hans.json), it will be skipped from further processing.
> Warning: Failed to read or parse localization file /root/.templateengine/packages/MudBlazor.Templates.0.6.5.nupkg(/content/mudblazor/.template.config/localize/templatestrings.zh-Hant.json), it will be skipped from further processing.
> Success: MudBlazor.Templates::0.6.5 installed the following templates:
> Template Name      Short Name  Language  Tags
> -----------------  ----------  --------  --------------------------------
> MudBlazor Web App  mudblazor   [C#]      Web/Blazor/WebAssembly/MudBlazor
> ```
> 
> ## Create new project (from tutorial):
> ```
> root@1c955b976efe:/app# dotnet new mudblazor --host wasm --name MyApplication
> Error: Invalid option(s):
> --host
>    '--host' is not a valid option
> wasm
>    'wasm' is not a valid option
> 
> For more information, run:
>    dotnet new mudblazor -h
> 
> For details on the exit code, refer to https://aka.ms/templating-exit-codes#127
> ```

New template has new operations check the readme or use -h for help as stated in your response.

https://github.com/MudBlazor/Templates/blob/dev/README.md
