### ISSUE TITLE
No Exception information shown

### ISSUE THREAD

**Issue by Apflkuacha** [Garderoben/MudBlazor.Templates#451]
I just created a project with the new .NET8 Template (Interactive Mode: Server) and added that it throws an Exception on button pressed. Just added `throw new Exception("test");` The result is that the page doesn't respond any more after I clicked the button and no information about an Exception is shown. 

On the original .NET8 Template (without Blazor) a Message is shown like this: `An unhandled error has occurred. Reload`
How to show such a Message in MudBlazor? That should be included in the template.

**Comment by d00lar** [comment]
add ` <div id="blazor-error-ui"> <span style="color:black">An unhandled error has occurred.</span> <a href="" class="reload">Reload</a> <a class="dismiss">🗙</a> </div>`
to routes.razor / index.html / depend on server/client side.
