### ISSUE TITLE
Interactivity does not work in MudBlazor WASM template for Visual Studio for .NET 8

### ISSUE THREAD

**Issue by mciprijanovic** [Garderoben/MudBlazor.Templates#458]
### Bug type

Component

### Component name

TextField, Button

### What happened?

Simply start installed MudBlazor WASM template in Visual Studio 2022 for .NET8 without any coding and it will not work. When going to Counter page and clicking the button, event is not fired. All other controls do not show interactivity like drawer, TextField etc. As I can see mode is set to IntractiveWebAssembly in routes and Head outlet, so, I don't know what is missing there sine that template is provided by MudBlazor people I suppose...

### Expected behavior

Expected behavior is that interactivity will work on MudBlazor components. For example button click would be fired and counter would increase on the counter page.

### Reproduction link

https://try.mudblazor.com/snippet/GaGoaSuKrbIzrfHH

### Reproduction steps

1. Install MudBlazor templates for Visual studio
2. Create new project by selecting MudBlazor Web Assembly template
3. Run the project
4. Navigate to Counter page
5. Click Counter button
6. Nothing happens and counter should increase (method in the razor page is not called)
...

### Version (bug)

.NET 8

### What browsers are you seeing the problem on?

Edge

### On which operating systems are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ScarletKuro** [comment]
Hi.

Can you upload your project in zip or as git repository?

**Comment by mciprijanovic** [comment]
Here is the zip file of the original project. It is a bit weird that noone complained since it is default project template in VS without changing a single line of code.
[MudBlazorWasmExample.zip](https://github.com/MudBlazor/Templates/files/14898552/MudBlazorWasmExample.zip)

**Comment by ScarletKuro** [comment]
@mikes-gh did we not post  a new version of template on nuget? I see it's still the buggy one with RC libraries etc.

**Comment by mikes-gh** [comment]
I just used current one.  Its version 1.0.0 with latest 8.* libs

**Comment by mikes-gh** [comment]
@mciprijanovic can you post `dotnet new list`

**Comment by ScarletKuro** [comment]
> @mciprijanovic can you post `dotnet new list`

this does not show the version tho.

I would recommend to run
```
dotnet new update MudBlazor.Templates
```
and try again?

**Comment by mciprijanovic** [comment]
Hi, it works with template updated to 1.0.0. However the question is: where is the difference? I have my own project, so I can not now create new one from scratch and copy all classes, namespaces etc.
MudBlazor Nuget package on the client project is MudBlazor 6.19.1 on both projects: new one with template 1.0.0 and old one 0.6.5, also, code of the mainPage, app component, Program.cs, Routes component and Counter page is more less the same... Which part should I replace in my project so the interactivity can work? What exactly is updated in the new template so I can do the same update in my project?
