### ISSUE TITLE
PWA not working

### ISSUE THREAD

**Issue by Sharafudeen** [Garderoben/MudBlazor.Templates#460]
[Link](https://learn.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-8.0&tabs=visual-studio) followed but not working in MudBlazor.Templates

**Comment by ScarletKuro** [comment]
> [Link](https://learn.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-8.0&tabs=visual-studio) followed but not working in MudBlazor.Templates

Hi,

As the link states, this is only supported with a standalone WebAssembly template, "Blazor WebAssembly Standalone App." Our `MudBlazor.Templates` contains only the "Web App" (render modes) templates that don't support PWA, and there is no standalone WebAssembly option in our templates. You need to create an original "Blazor WebAssembly Standalone App" from Visual Studio and add MudBlazor manually; it should work.
