### ISSUE TITLE
Authentication pages cause the app not to update mudblazor layers properly

### ISSUE THREAD

**Issue by pandalabs-dev** [Garderoben/MudBlazor.Templates#461]
Just start the project with added authentication pages from default as shown in the image
![image](https://github.com/MudBlazor/Templates/assets/31215706/8ec21e60-d4b6-4527-b159-0df7ff0ca4db)

When you are on home page try to click the MudIconButton to Close/Open the drawer, it works.

Then go to the account page to login for example, try to do the same, it doesnt close/open the drawer.

**Comment by hixtz** [comment]
Uploading not_working_blazor.mp4…

**Comment by pandalabs-dev** [comment]
https://github.com/MudBlazor/Templates/assets/31215706/ce78aaa0-392a-40c4-ab62-ae94718a1de5

**Comment by Anu6is** [comment]
Authentication pages are statically rendered, as such, interactive components (such as buttons) will not function once the page has been rendered. You can read more https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#static-server-side-rendering-static-ssr. 

This is expected Blazor behavior.

**Comment by ScarletKuro** [comment]
> This is expected Blazor behavior.

As it was said, this is expected.
