### ISSUE TITLE
MudIcon CreationTool

### ISSUE THREAD

**Issue by kurwanator1337** [Garderoben/MudBlazor.Templates#464]
Hi! Could you tell me if it's possible to create a tool for making icons for your product? When I'm doing it myself, it feels like an exhausting task to adjust the image so it’s not offset in any direction. Or just tell me that I'm doing it completely wrong :D

**Comment by ScarletKuro** [comment]
Hi, 

If you are talking about SVG icons, you just need to use an SVG editor with rich functionality. Set a 24x24 viewport, and the editors have tools to align the selected items both vertically and horizontally.

**Comment by kurwanator1337** [comment]
Ok, thank you! I'll try later.
