### ISSUE TITLE
How to view the template displayed on the homepage

### ISSUE THREAD

**Issue by Newbie-JZ** [Garderoben/MudBlazor.Templates#470]
Where can I find the templates showcased on the homepage (https://mudblazor.com/) that offer a more visually appealing and user-friendly experience?

**Comment by ScarletKuro** [comment]
Hi,

> Where can I find the templates showcased on the homepage (https://mudblazor.com/) that offer a more visually appealing and user-friendly experience?

It's just a render. Something "close" was in the old dashboard https://mudblazorwithjwt.azurewebsites.net/personal/dashboard. You can find the source code here: https://github.com/TheDayIsMyEnemy/BlazorTemplates/tree/admin-dashboard, but it's pretty old and unsupported.

**Comment by Newbie-JZ** [comment]
Okay, thank you. I still suggest providing a template page with richer content, which is more user-friendly and faster for beginners like me to get started with

**Comment by ScarletKuro** [comment]
> Okay, thank you. I still suggest providing a template page with richer content, which is more user-friendly and faster for beginners like me to get started with

The point of the templates is to provide a startup setup that saves time and avoids confusion when dealing with WebApps. The `MudBlazor.Templates` is a fork of the original Microsoft templates, but with MudBlazor components. We don't plan to change this, as the maintenance cost would increase with each new .NET runtime release and its features.

To continue, you can use the documentation from https://mudblazor.com/ and copy-paste the examples into your project to experiment with them.
