### ISSUE TITLE
Logout returns 405, static checkbox does not work on remember me

### ISSUE THREAD

**Issue by Sinister-Dexter** [Garderoben/MudBlazor.Templates#471]
Logout not working on templates, returns 405. MudStaticCheckBox also does not work on the remember me checkbox.

**Comment by horrorhound** [comment]
Just noticed this today also... Started a new project from the .net 8 template to migrate an old .net 7 project.

**Comment by horrorhound** [comment]
Use --interactivity Server and the remember me check box will work.

But the Logout button fails after logging in.   Haven't looked into why yet.

**Comment by horrorhound** [comment]
Looks like Identity Extensions has a MapPost /Logout which is expected to be used for Logouts in the MudBlazor Template..

I had to update my logout link to this:

      @*<MudNavLink Href="@($"Account/Logout?ReturnUrl={currentUrl}")" Match="NavLinkMatch.Prefix" Icon="@Icons.Material.Filled.Add">Logout</MudNavLink>*@
      <form method="post" action="Account/Logout">
        <MudButton ButtonType="ButtonType.Submit" StartIcon="@Icons.Material.Filled.Logout" Color="@Color.Default" Variant="Variant.Filled">Logout</MudButton>
        <input type="hidden" id="returnUrl" name="returnUrl" value="@currentUrl" />
        <AntiforgeryToken />
      </form>

**Comment by ScarletKuro** [comment]
Released 2.1.0 https://www.nuget.org/packages/MudBlazor.Templates/2.1.0 with the above fix.
Not sure about the checkbox

> Use --interactivity Server and the remember me check box will work.

@Anu6is could it be a `MudStaticCheckBox` bug? I don't really see what the issue is, they code is pretty simple:
```razor
<MudStaticCheckBox For="@(() => Input.RememberMe)" @bind-Value="Input.RememberMe">Remember me</MudStaticCheckBox>
```

**Comment by Anu6is** [comment]
@ScarletKuro I'd have to look into it. 
Also came across this https://github.com/dotnet/aspnetcore/issues/52273 which I have to find a workaround for.

Edit: Looks like the issue is actually related to what I linked ^

**Comment by Anu6is** [comment]
@Sinister-Dexter update the StaticInput package to `2.1.1` and add the following to the `body` tag in your `App.razor`  

`<script src="_content/Extensions.MudBlazor.StaticInput/NavigationObserver.js"></script>`

See if that resolves the `CheckBox` issue

**Comment by ScarletKuro** [comment]
https://www.nuget.org/packages/MudBlazor.Templates/2.2.0 should address the `MudStaticCheckBox` issue.
