### ISSUE TITLE
Mudblazor Web App places appsettings.json in root of client

### ISSUE THREAD

**Issue by Sinister-Dexter** [Garderoben/MudBlazor.Templates#474]
Mudblazor Web App template places appsettings.json in root of client, this should be in wwwroot. Causes publish error "Found multiple publish output files with the same relative path"

**Comment by Anu6is** [comment]
The templates are based off of the Microsoft templates which places appsettings in the root, no in wwwroot.

**Comment by ScarletKuro** [comment]
> The templates are based off of the Microsoft templates which places appsettings in the root, no in wwwroot.

Apparently, I created a clean project from the MS templates, and for the Client, it's indeed in `wwwroot`, not in the root. I'm not really sure from which branch or tag Jon forked it. Maybe they fixed it, but it's hard to tell at this point.

**Comment by ScarletKuro** [comment]
https://www.nuget.org/packages/MudBlazor.Templates/2.2.0 should address this
