### ISSUE TITLE
StaticInput causes OnInitializedAsync to be called three times

### ISSUE THREAD

**Issue by jbngan** [Garderoben/MudBlazor.Templates#476]
I created a fresh Blazor Server App and noticed that OnInitializedAsync was called three times. This issue was resolved when I removed StaticInput from App.razor.

`<script src="_content/Extensions.MudBlazor.StaticInput/NavigationObserver.js"></script>`

**Comment by jbngan** [comment]
FYI: I putted a Console.WriteLine into Weather.razor.

```c#
protected override async Task OnInitializedAsync()
{
    Console.WriteLine("{0} load forecast", DateTime.Now.Second);
    ...
}
```

**Comment by ScarletKuro** [comment]
Hi.

Please, forward the issue to https://github.com/0phois/MudBlazor.StaticInput
