### ISSUE TITLE
.NET 9 Templates release date?

### ISSUE THREAD

**Issue by omidkrad** [Garderoben/MudBlazor.Templates#481]
.NET 9 was released on Nov 12, 2024 with new Blazor Web App templates.

[Blazor 9 Release Notes](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-9.0#blazor)

What's the plan for the updated MudBlazor templates? Thanks.

**Comment by ScarletKuro** [comment]
Hi,

We are aware of the .NET 9 release, and we are currently working on v8 of MudBlazor and its support for .NET 9. Once we have completed that and have some spare time, we will update the templates to .NET 9 as well (the templates alo depend on the `Extensions.MudBlazor.StaticInput` dependency, which also needs to be updated first).

For now, we can't do everything at once.

**Comment by omidkrad** [comment]
Thanks!
