### ISSUE TITLE
isntall Mudbalzor templates from dev branch for dotnet 9

### ISSUE THREAD

**Issue by andresparrab** [Garderoben/MudBlazor.Templates#488]
Hello!

We are going to start a project in dotnet 9 and would love to use mudblazor but when we install the tremplate we can only choose dotnet 8.

I saw in your dev branch that you already have support for dotnet 9.
How can we do to install the template from dev?
i know is not 100% stable as it is in dev. But we can try anyway ;)

**Comment by ScarletKuro** [comment]
Hi.

> I saw in your dev branch that you already have support for dotnet 9.

That support is only for the CI builds, there are no templates with .NET9 in dev branch.

But there is this PR https://github.com/MudBlazor/Templates/pull/482 that is waiting for MudBlazor v8 release.
You can fork this PR and install it with:
```
dotnet new install /src/mudblazor --force
```
And try it out.

**Comment by andresparrab** [comment]
it worked perfectly thank you.
