### ISSUE TITLE
no index in wwwrot folder?

### ISSUE THREAD

**Issue by andresparrab** [Garderoben/MudBlazor.Templates#489]
When creating a Mudblazor wit Autto(Server & WebbAssembly) the application run and everything.
I idid a pipeline in github to create try and create an static page to host in github.. but github need an index.html that should be created when doing

cd MyMudBlazorApp.Client
dotnet publish -c Release -o build
mv BuyBuddy.Client/build public

the build folder contains 

<img width="386" alt="image" src="https://github.com/user-attachments/assets/49c43b2d-d9f0-46ce-a100-879998156aa9">

and wwwroot
<img width="420" alt="image" src="https://github.com/user-attachments/assets/394ebcd3-19fe-4a86-8705-f98fcd57a70a">
as you can see there is not index.html so i cant have the static page in github pages.

Is it missing or do I do something wrong

**Comment by ScarletKuro** [comment]
> Is it missing or do I do something wrong

`index.html` doesn't exist in the Blazor Web App template, it's not suitable for GitHub Pages. You need the "Blazor WebAssembly Standalone App" template, which includes it, but we don't provide that template. Therefore, you'll need to create the basic one from Microsoft and integrate MudBlazor, which shouldn't be very difficult.

**Comment by andresparrab** [comment]
thankk you i will try that way.

The basic one one from Microsoft.. do you mean create a Blazor WebAssembly standalone app and copy the index.html file to the Balzor wwwroot folder?

**Comment by ScarletKuro** [comment]
> The basic one one from Microsoft.. do you mean create a Blazor WebAssembly standalone app and copy the index.html file to the Balzor wwwroot folder?

No no, that's not how it works. Create "Blazor WebAssembly Standalone App" and move all your stuff there instead if you want to be able deploy to Github Pages. As I said, "Blazor Web App" is not suited for Github Pages as it always requires the server part.

**Comment by andresparrab** [comment]
Got it. thanks for the clarification.
Maybe just deploy the mudblazor in azure and for the github pages just have some autodocumentation page.

**Comment by ScarletKuro** [comment]
I would generally recommend reading the Microsoft documentation or articles about the different hosting models, such as this one: https://medium.com/@meghnav274/blazor-server-vs-blazor-webassembly-vs-blazor-web-app-8fe8fc1cefeb.

There are three types: Blazor Server (deprecated, no longer provided by us or Microsoft), Blazor WebAssembly (standalone), and Blazor Web App (which has different modes: Auto, Interactive Server, Interactive WebAssembly, and Static SSR).

They all differ from each other. Blazor WebAssembly is purely client-side and is not the same as Blazor Web App even with Interactive WebAssembly, as the latter uses prerendering for faster loading, which requires a server on the initial load. In contrast, Blazor WebAssembly standalone will display a loading screen while downloading all the runtime assemblies.

The "Auto" mode you mentioned can utilize both Server and Client.

So, I would advise to google it, as there are many nuances, but it will help you become more fluent in Blazor.
