### ISSUE TITLE
Imports not working on newly initialised template project

### ISSUE THREAD

**Issue by karlschriek** [Garderoben/MudBlazor.Templates#490]
Installed templates with:

`dotnet new install MudBlazor.Templates`

Created project with:

`dotnet new mudblazor --interactivity Server --auth Individual -o MyProject.MudBlazor`

Get lots of red squigglies with due to imports not being recognised. In particular,  these two in _imports.razor:

```c#
@using MudBlazor.StaticInput
@using MudBlazor.Services
```

`Cannot resolve symbol 'StaticInput'`, `Cannot resolve symbol 'Services'`

csproj looks like this:

```csproj
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.*" />
    <PackageReference Include="MudBlazor" Version="7.*" />
    <PackageReference Include="Extensions.MudBlazor.StaticInput" Version="2.*" />
  </ItemGroup>

```

Interestingly, in Program.cs this works:

```c#
using MudBlazor.StaticInput
using MudBlazor.Services
```

I am using DotNet 8.

Am I missing something, or is the template broken?

**Comment by karlschriek** [comment]
Nevermind, this is because my project (and hence my root namespace) is called "MyProject.MudBlazor", which conflicts with the "MudBlazor" package.

**Comment by MAHarby** [comment]
Thanks for clarifying, I just made the same mistake and getting red squiggles everywhere as well.
