### ISSUE TITLE
Repeated 'rejoining the server' on MudBlazor + identity template upgraded to net 9

### ISSUE THREAD

**Issue by jpmikkers** [Garderoben/MudBlazor.Templates#491]
- create a new project like this:
    `dotnet new mudblazor --framework net8.0 --interactivity Server --auth Individual --all-interactive`
- upgrade the project to net9
- run it. I use firefox as browser. After clicking the login button, the 'rejoining the server' dialog pops up, sometimes once, sometimes multiple times in a row. Eventually it does seem to settle, so its not precisely an issue, just looks a bit ugly.

But there's good news: the multiple disconnect/reconnect problem goes away when I use this in App.razor:

```csharp
        //old from template:
        //private IComponentRenderMode? RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account")
        //    ? null
        //    : InteractiveAuto;

        private IComponentRenderMode? RenderModeForPage =>
            HttpContext.AcceptsInteractiveRouting() ? InteractiveServer : null;
```

And change Components/Accounts/Pages/_Imports.razor to:

```
@layout AccountLayout

// this ensures all pages under Account will use static serverside rendering (static SSR)
// see: Static SSR pages in a globally-interactive app
// https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-9.0
@attribute [ExcludeFromInteractiveRouting]
```

**Comment by jpmikkers** [comment]
Update: I see this has already been taken care of in PR #482 !

**Comment by saddamhossain** [comment]
Hi, could you share how I can get the template for .NET 9?

**Comment by jpmikkers** [comment]
Click this pull request: https://github.com/MudBlazor/Templates/pull/482
or here is the related branch : https://github.com/jperson2000/MudBlazor.Templates/tree/feature/net9
or you could wait for the pull request to be merged 👍
