### ISSUE TITLE
MudBlazor.ThemeManager package is not visible for searching through Nuget package manager

### ISSUE THREAD

**Issue by nguyenhthai** [Garderoben/MudBlazor.Templates#6]
Not sure if this is the right place to file this issue but while looking for the ThemeManager package, I could not find it through Nuget package manager. However, adding it through PackageReference via .csproj file does pull the correct package.

**Comment by gtejeda** [comment]
+1

**Comment by Garderoben** [comment]
Its intentional for now, its not documented anywhere how to use it. And it has some bugs and missing features. Its more for demo purpose, of what you can do with just the theme in MudBlazor.

I plan to add elevation options and theme presets in the feature.

**Comment by gtejeda** [comment]
Thanks,
FANTASTIC JOB you guys are doing with the theme!

**Comment by rakeshkgsg** [comment]
Hi,
Will you guys be releasing the thememanager - keen to use it and learn about it.
